### ISSUE TITLE
Unable to merge files with a non-UTF-8 encoding

### ISSUE THREAD

**Issue by Astralius** [seyfiyumlu/vMerge2022#1]
Hi @seyfiyumlu! First of all, great extension! I really like the notion you took here, as the only extension in marketplace yours allow to really merge changesets one-by-one automatically and keep history of changesets in target branch 👍👍. It has few issues though...

Probably the most irritating one is that you cannot merge a changeset if at least one file has encoding other than WPF-8 (Version: 2.0.9 (latest), IDE: Visual Studio Professional 2022). This happens e.g. if you like to check-in a .doc file / .pdf or other non-code / non-plaintext file. You do get a pop-up informing about the issue, but in our case this contributes to about 20% of our repo and really reduces the benefit of automatic merging (you need to stop after a few changesets, merge manually, then go back to changesets view, select changesets, wait for merge window to load etc.).

![UTF-8 issue vMerge](https://user-images.githubusercontent.com/6178718/157186444-bf32e0b1-bbd4-4a8d-b749-f63877501ec6.png)

Why do you need to depend on UTF-8 encoding precisely? TFVC supports other encodings perfectly. Possible to fix?

I also have other issues to bring up. Please let me know if you want and have time to address them. I'm not really familiar with extensions development so cannot contribute directly here :<

**Comment by seyfiyumlu** [comment]
hi, this control is necessery for our use of turkish encoding system. I did changed the control depends on a parameter below. you can download the 2.0.10 version.
![image](https://user-images.githubusercontent.com/27860010/157432489-766e8e1c-753f-4ce1-9f93-309c2491c3fe.png)
