### ISSUE TITLE
vMerge 2.0.10: Cannot load Merge window / vMerge Options

### ISSUE THREAD

**Issue by Astralius** [seyfiyumlu/vMerge2022#2]
Hello,

I use vMerge frequently to merge TFCS changesets. Every now and then, I experience an issue where, after selecting desired changesets in the Changesets View and clicking "Perform Merge" I get a progress bar and when it reaches 100%, nothing happens.. (the actual Merge window is not displayed). When this happens, this is accompanied with another issue as below:
![image](https://user-images.githubusercontent.com/6178718/164231162-1293423b-7038-4dfc-88b8-765ca79222ae.png)

Versions:
vMerge 2.0.10
IDE: Visual Studio Professional 2022, Version 17.1.5
OS: Windows 10 Version 21H2 (OS Build 19044.1645)

See attached log file.
[vMerge, Version=2.0.10.0, Culture=neutral, PublicKeyToken=133d2d8b3063fdce.log](https://github.com/seyfiyumlu/vMerge2022/files/8521519/vMerge.Version.2.0.10.0.Culture.neutral.PublicKeyToken.133d2d8b3063fdce.log)

P.S. Thank you for solving the previous issue. Works like a charm!

**Comment by seyfiyumlu** [comment]
you can try the new version on the market.
